/*
 * Mycelium
 * Copyright (C) 2022  JNNGL
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


#include "mud_brick_wall_block.h"

MudBrickWallBlock::MudBrickWallBlock() = default;
MudBrickWallBlock::~MudBrickWallBlock() = default;

short MudBrickWallBlock::getId() const {
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13692;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13693;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13694;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13695;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13696;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13697;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13698;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13699;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13700;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13701;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13702;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13703;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13704;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13705;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13706;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13707;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13708;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13709;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13710;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13711;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13712;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13713;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13714;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13715;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13716;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13717;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13718;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13719;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13720;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13721;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13722;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13723;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13724;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13725;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13726;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13727;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13728;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13729;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13730;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13731;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13732;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13733;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13734;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13735;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13736;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13737;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13738;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13739;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13740;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13741;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13742;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13743;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13744;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13745;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13746;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13747;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13748;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13749;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13750;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13751;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13752;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13753;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13754;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13755;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13756;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13757;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13758;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13759;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13760;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13761;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13762;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13763;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13764;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13765;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13766;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13767;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13768;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13769;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13770;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13771;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13772;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13773;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13774;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13775;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13776;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13777;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13778;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13779;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13780;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13781;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13782;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13783;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13784;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13785;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13786;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13787;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13788;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13789;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13790;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13791;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13792;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13793;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13794;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13795;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13796;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13797;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13798;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13799;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13800;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13801;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13802;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13803;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13804;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13805;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13806;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13807;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13808;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13809;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13810;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13811;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13812;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13813;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13814;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13815;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13816;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13817;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13818;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13819;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13820;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13821;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13822;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13823;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13824;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13825;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13826;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13827;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13828;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13829;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13830;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13831;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13832;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13833;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13834;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13835;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13836;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13837;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13838;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13839;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13840;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13841;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13842;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13843;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13844;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13845;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13846;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13847;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13848;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13849;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13850;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13851;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13852;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13853;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13854;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13855;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13856;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13857;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13858;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13859;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13860;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13861;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13862;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13863;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13864;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13865;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13866;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13867;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13868;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13869;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13870;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13871;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13872;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13873;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13874;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13875;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13876;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13877;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13878;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13879;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13880;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13881;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13882;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13883;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13884;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13885;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13886;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13887;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13888;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13889;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13890;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13891;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13892;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13893;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13894;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13895;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13896;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13897;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13898;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13899;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13900;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13901;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13902;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13903;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13904;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13905;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13906;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13907;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13908;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13909;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13910;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13911;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13912;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13913;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13914;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13915;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13916;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13917;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13918;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13919;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13920;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13921;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13922;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13923;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13924;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13925;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13926;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13927;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13928;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13929;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13930;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13931;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13932;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13933;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13934;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13935;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13936;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13937;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13938;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13939;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13940;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13941;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13942;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13943;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13944;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13945;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13946;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13947;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13948;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13949;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13950;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13951;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13952;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13953;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13954;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13955;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13956;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13957;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13958;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13959;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13960;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13961;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13962;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13963;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13964;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13965;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13966;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13967;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13968;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13969;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13970;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13971;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13972;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13973;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13974;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13975;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13976;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13977;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13978;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13979;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13980;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13981;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13982;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13983;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13984;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13985;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13986;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13987;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13988;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13989;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13990;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13991;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13992;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13993;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 13994;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 13995;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 13996;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 13997;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 13998;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 13999;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 14000;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 14001;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 14002;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 14003;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 14004;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 14005;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 14006;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 14007;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 14008;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 14009;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 14010;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 14011;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 14012;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 14013;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 14014;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 14015;
  return 13695;
}

std::shared_ptr<Block> MudBrickWallBlock::clone() const {
  std::shared_ptr<MudBrickWallBlock> copy = std::make_shared<MudBrickWallBlock>();
  copy->east = east;
  copy->north = north;
  copy->south = south;
  copy->up = up;
  copy->waterlogged = waterlogged;
  copy->west = west;
  return copy;
}
