/*
 * Mycelium
 * Copyright (C) 2022  JNNGL
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


#include "polished_blackstone_wall_block.h"

PolishedBlackstoneWallBlock::PolishedBlackstoneWallBlock() = default;
PolishedBlackstoneWallBlock::~PolishedBlackstoneWallBlock() = default;

short PolishedBlackstoneWallBlock::getId() const {
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 17986;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 17987;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 17988;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 17989;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 17990;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 17991;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 17992;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 17993;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 17994;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 17995;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 17996;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 17997;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 17998;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 17999;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18000;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18001;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18002;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18003;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18004;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18005;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18006;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18007;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18008;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18009;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18010;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18011;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18012;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18013;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18014;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18015;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18016;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18017;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18018;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18019;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18020;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18021;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18022;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18023;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18024;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18025;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18026;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18027;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18028;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18029;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18030;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18031;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18032;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18033;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18034;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18035;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18036;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18037;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18038;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18039;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18040;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18041;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18042;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18043;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18044;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18045;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18046;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18047;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18048;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18049;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18050;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18051;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18052;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18053;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18054;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18055;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18056;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18057;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18058;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18059;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18060;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18061;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18062;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18063;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18064;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18065;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18066;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18067;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18068;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18069;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18070;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18071;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18072;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18073;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18074;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18075;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18076;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18077;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18078;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18079;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18080;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18081;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18082;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18083;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18084;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18085;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18086;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18087;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18088;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18089;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18090;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18091;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18092;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18093;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18094;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18095;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18096;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18097;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18098;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18099;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18100;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18101;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18102;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18103;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18104;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18105;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18106;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18107;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18108;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18109;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18110;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18111;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18112;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18113;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18114;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18115;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18116;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18117;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18118;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18119;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18120;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18121;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18122;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18123;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18124;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18125;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18126;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18127;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18128;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18129;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18130;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18131;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18132;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18133;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18134;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18135;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18136;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18137;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18138;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18139;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18140;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18141;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18142;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18143;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18144;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18145;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18146;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18147;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18148;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18149;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18150;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18151;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18152;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18153;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18154;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18155;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18156;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18157;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18158;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18159;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18160;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18161;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18162;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18163;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18164;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18165;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18166;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18167;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18168;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18169;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18170;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18171;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18172;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18173;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18174;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18175;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18176;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18177;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18178;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18179;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18180;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18181;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18182;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18183;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18184;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18185;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18186;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18187;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18188;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18189;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18190;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18191;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18192;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18193;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18194;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18195;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18196;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18197;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18198;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18199;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18200;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18201;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18202;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18203;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18204;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18205;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18206;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18207;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18208;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18209;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18210;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18211;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18212;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18213;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18214;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18215;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18216;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18217;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18218;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18219;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18220;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18221;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18222;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18223;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18224;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18225;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18226;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18227;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18228;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18229;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18230;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18231;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18232;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18233;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18234;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18235;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18236;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18237;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18238;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18239;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18240;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18241;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18242;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18243;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18244;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18245;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18246;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18247;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18248;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18249;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18250;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18251;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18252;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18253;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18254;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18255;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18256;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18257;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18258;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18259;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18260;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18261;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18262;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18263;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18264;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18265;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18266;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18267;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18268;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18269;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18270;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18271;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18272;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18273;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18274;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18275;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18276;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18277;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18278;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18279;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18280;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18281;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18282;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18283;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18284;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18285;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18286;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18287;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18288;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18289;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18290;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18291;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18292;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18293;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18294;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18295;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18296;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18297;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18298;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18299;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18300;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18301;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18302;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18303;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 18304;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 18305;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 18306;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 18307;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 18308;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 18309;
  return 17989;
}

std::shared_ptr<Block> PolishedBlackstoneWallBlock::clone() const {
  std::shared_ptr<PolishedBlackstoneWallBlock> copy = std::make_shared<PolishedBlackstoneWallBlock>();
  copy->east = east;
  copy->north = north;
  copy->south = south;
  copy->up = up;
  copy->waterlogged = waterlogged;
  copy->west = west;
  return copy;
}
