/*
 * Mycelium
 * Copyright (C) 2022  JNNGL
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


#include "sandstone_wall_block.h"

SandstoneWallBlock::SandstoneWallBlock() = default;
SandstoneWallBlock::~SandstoneWallBlock() = default;

short SandstoneWallBlock::getId() const {
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 14988;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 14989;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 14990;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 14991;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 14992;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 14993;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 14994;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 14995;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 14996;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 14997;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 14998;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 14999;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15000;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15001;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15002;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15003;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15004;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15005;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15006;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15007;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15008;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15009;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15010;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15011;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15012;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15013;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15014;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15015;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15016;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15017;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15018;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15019;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15020;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15021;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15022;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15023;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15024;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15025;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15026;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15027;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15028;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15029;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15030;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15031;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15032;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15033;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15034;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15035;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15036;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15037;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15038;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15039;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15040;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15041;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15042;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15043;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15044;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15045;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15046;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15047;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15048;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15049;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15050;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15051;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15052;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15053;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15054;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15055;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15056;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15057;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15058;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15059;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15060;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15061;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15062;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15063;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15064;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15065;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15066;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15067;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15068;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15069;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15070;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15071;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15072;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15073;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15074;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15075;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15076;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15077;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15078;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15079;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15080;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15081;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15082;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15083;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15084;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15085;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15086;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15087;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15088;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15089;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15090;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15091;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15092;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15093;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15094;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15095;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15096;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15097;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15098;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15099;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15100;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15101;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15102;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15103;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15104;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15105;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15106;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15107;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15108;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15109;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15110;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15111;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15112;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15113;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15114;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15115;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15116;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15117;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15118;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15119;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15120;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15121;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15122;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15123;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15124;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15125;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15126;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15127;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15128;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15129;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15130;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15131;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15132;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15133;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15134;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15135;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15136;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15137;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15138;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15139;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15140;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15141;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15142;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15143;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15144;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15145;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15146;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15147;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15148;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15149;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15150;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15151;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15152;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15153;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15154;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15155;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15156;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15157;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15158;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15159;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15160;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15161;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15162;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15163;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15164;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15165;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15166;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15167;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15168;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15169;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15170;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15171;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15172;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15173;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15174;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15175;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15176;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15177;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15178;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15179;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15180;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15181;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15182;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15183;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15184;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15185;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15186;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15187;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15188;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15189;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15190;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15191;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15192;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15193;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15194;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15195;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15196;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15197;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15198;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15199;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15200;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15201;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15202;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15203;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15204;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15205;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15206;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15207;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15208;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15209;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15210;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15211;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15212;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15213;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15214;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15215;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15216;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15217;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15218;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15219;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15220;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15221;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15222;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15223;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15224;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15225;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15226;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15227;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15228;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15229;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15230;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15231;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15232;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15233;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15234;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15235;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15236;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15237;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15238;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15239;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15240;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15241;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15242;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15243;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15244;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15245;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15246;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15247;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15248;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15249;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15250;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15251;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15252;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15253;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15254;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15255;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15256;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15257;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15258;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15259;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15260;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15261;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15262;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15263;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15264;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15265;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15266;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15267;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15268;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15269;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15270;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15271;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15272;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15273;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15274;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15275;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15276;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15277;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15278;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15279;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15280;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15281;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15282;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15283;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15284;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15285;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15286;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15287;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15288;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15289;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15290;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15291;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15292;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15293;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15294;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15295;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15296;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15297;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15298;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15299;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15300;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15301;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15302;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15303;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15304;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15305;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 15306;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 15307;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 15308;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 15309;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 15310;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 15311;
  return 14991;
}

std::shared_ptr<Block> SandstoneWallBlock::clone() const {
  std::shared_ptr<SandstoneWallBlock> copy = std::make_shared<SandstoneWallBlock>();
  copy->east = east;
  copy->north = north;
  copy->south = south;
  copy->up = up;
  copy->waterlogged = waterlogged;
  copy->west = west;
  return copy;
}
