#pragma once

enum CatVariant {
  CAT_TABBY = 0,
  CAT_BLACK = 1,
  CAT_RED = 2,
  CAT_SIAMESE = 3,
  CAT_BRITISH_SHORTHAIR = 4,
  CAT_CALICO = 5,
  CAT_PERSIAN = 6,
  CAT_RAGDOLL = 7,
  CAT_WHITE = 8,
  CAT_JELLIE = 9,
  CAT_ALL_BLACK = 10
};