#ifndef MYCELIUM_DIFFICULTY_H
#define MYCELIUM_DIFFICULTY_H

enum DIFFICULTY {
    DIFFICULTY_PEACEFUL = 0,
    DIFFICULTY_EASY = 1,
    DIFFICULTY_NORMAL = 2,
    DIFFICULTY_HARD = 3
};

#endif //MYCELIUM_DIFFICULTY_H
