#ifndef MYCELIUM_GAMEMODE_H
#define MYCELIUM_GAMEMODE_H

enum GAMEMODE {
    GM_SURVIVAL = 0,
    GM_CREATIVE = 1,
    GM_ADVENTURE = 2,
    GM_SPECTATOR = 3,
    PREV_GM_SURVIVAL = 0,
    PREV_GM_CREATIVE = 1,
    PREV_GM_ADVENTURE = 2,
    PREV_GM_SPECTATOR = 3,
    PREV_GM_DEFAULT = -1
};

#endif //MYCELIUM_GAMEMODE_H
