#pragma once

#define REGISTER_CHANNEL "minecraft:register"
#define UNREGISTER_CHANNEL "minecraft:unregister"

#define BRAND_CHANNEL "minecraft:brand"
#define LEGACY_BRAND_CHANNEL "MC|Brand"
#define DEBUG_PATHS_CHANNEL "minecraft:debug/paths"
#define DEBUG_NEIGHBORS_UPDATE_CHANNEL "minecraft:debug/neighbors_update"
#define DEBUG_CAVES_CHANNEL "minecraft:debug/caves"
#define DEBUG_STRUCTURES_CHANNEL "minecraft:debug/structures"
#define DEBUG_WORLDGEN_ATTEMPT_CHANNEL "minecraft:debug/worldgen_attempt"
#define DEBUG_POI_TICKET_COUNT_CHANNEL "minecraft:debug/poi_ticket_count"
#define DEBUG_POI_ADDED_CHANNEL "minecraft:debug/poi_added"
#define DEBUG_POI_REMOVED_CHANNEL "minecraft:debug/poi_removed"
#define DEBUG_VILLAGE_SECTIONS_CHANNEL "minecraft:debug/village_sections"
#define DEBUG_GOAL_SELECTOR_CHANNEL "minecraft:debug/goal_selector"
#define DEBUG_BRAIN_CHANNEL "minecraft:debug/brain"
#define DEBUG_BEE_CHANNEL "minecraft:debug/bee"
#define DEBUG_HIVE_CHANNEL "minecraft:debug/hive"
#define DEBUG_GAME_TEST_ADD_MARKER_CHANNEL "minecraft:debug/game_test_add_marker"
#define DEBUG_GAME_TEST_CLEAR_CHANNEL "minecraft:debug/game_test_clear"
#define DEBUG_RAIDS_CHANNEL "minecraft:debug/raids"
#define DEBUG_GAME_EVENT_CHANNEL "minecraft:debug/game_event"
#define DEBUG_GAME_EVENT_LISTENERS_CHANNEL "minecraft:debug/game_event_listeners"