/*
 * Mycelium
 * Copyright (C) 2022  JNNGL
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


#include "mossy_cobblestone_wall_block.h"

MossyCobblestoneWallBlock::MossyCobblestoneWallBlock() = default;
MossyCobblestoneWallBlock::~MossyCobblestoneWallBlock() = default;

short MossyCobblestoneWallBlock::getId() const {
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6573;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6574;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6575;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6576;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6577;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6578;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6579;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6580;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6581;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6582;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6583;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6584;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6585;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6586;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6587;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6588;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6589;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6590;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6591;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6592;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6593;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6594;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6595;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6596;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6597;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6598;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6599;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6600;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6601;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6602;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6603;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6604;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6605;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6606;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6607;
  if (east == EAST_NONE && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6608;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6609;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6610;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6611;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6612;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6613;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6614;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6615;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6616;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6617;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6618;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6619;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6620;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6621;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6622;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6623;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6624;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6625;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6626;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6627;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6628;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6629;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6630;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6631;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6632;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6633;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6634;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6635;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6636;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6637;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6638;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6639;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6640;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6641;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6642;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6643;
  if (east == EAST_NONE && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6644;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6645;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6646;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6647;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6648;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6649;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6650;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6651;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6652;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6653;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6654;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6655;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6656;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6657;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6658;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6659;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6660;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6661;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6662;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6663;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6664;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6665;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6666;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6667;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6668;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6669;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6670;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6671;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6672;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6673;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6674;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6675;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6676;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6677;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6678;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6679;
  if (east == EAST_NONE && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6680;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6681;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6682;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6683;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6684;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6685;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6686;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6687;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6688;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6689;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6690;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6691;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6692;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6693;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6694;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6695;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6696;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6697;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6698;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6699;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6700;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6701;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6702;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6703;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6704;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6705;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6706;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6707;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6708;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6709;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6710;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6711;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6712;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6713;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6714;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6715;
  if (east == EAST_LOW && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6716;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6717;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6718;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6719;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6720;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6721;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6722;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6723;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6724;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6725;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6726;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6727;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6728;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6729;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6730;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6731;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6732;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6733;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6734;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6735;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6736;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6737;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6738;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6739;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6740;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6741;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6742;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6743;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6744;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6745;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6746;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6747;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6748;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6749;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6750;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6751;
  if (east == EAST_LOW && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6752;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6753;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6754;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6755;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6756;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6757;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6758;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6759;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6760;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6761;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6762;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6763;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6764;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6765;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6766;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6767;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6768;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6769;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6770;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6771;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6772;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6773;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6774;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6775;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6776;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6777;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6778;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6779;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6780;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6781;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6782;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6783;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6784;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6785;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6786;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6787;
  if (east == EAST_LOW && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6788;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6789;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6790;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6791;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6792;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6793;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6794;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6795;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6796;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6797;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6798;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6799;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6800;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6801;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6802;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6803;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6804;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6805;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6806;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6807;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6808;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6809;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6810;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6811;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6812;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6813;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6814;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6815;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6816;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6817;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6818;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6819;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6820;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6821;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6822;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6823;
  if (east == EAST_TALL && north == NORTH_NONE && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6824;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6825;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6826;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6827;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6828;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6829;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6830;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6831;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6832;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6833;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6834;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6835;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6836;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6837;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6838;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6839;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6840;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6841;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6842;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6843;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6844;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6845;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6846;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6847;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6848;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6849;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6850;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6851;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6852;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6853;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6854;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6855;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6856;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6857;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6858;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6859;
  if (east == EAST_TALL && north == NORTH_LOW && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6860;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6861;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6862;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6863;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6864;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6865;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6866;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6867;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6868;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6869;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6870;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6871;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_NONE && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6872;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6873;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6874;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6875;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6876;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6877;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6878;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6879;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6880;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6881;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6882;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6883;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_LOW && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6884;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6885;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6886;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6887;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6888;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6889;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_TRUE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6890;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_NONE) return 6891;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_LOW) return 6892;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_TRUE && west == WEST_TALL) return 6893;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_NONE) return 6894;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_LOW) return 6895;
  if (east == EAST_TALL && north == NORTH_TALL && south == SOUTH_TALL && up == UP_FALSE && waterlogged == WATERLOGGED_FALSE && west == WEST_TALL) return 6896;
  return 6576;
}

std::shared_ptr<Block> MossyCobblestoneWallBlock::clone() const {
  std::shared_ptr<MossyCobblestoneWallBlock> copy = std::make_shared<MossyCobblestoneWallBlock>();
  copy->east = east;
  copy->north = north;
  copy->south = south;
  copy->up = up;
  copy->waterlogged = waterlogged;
  copy->west = west;
  return copy;
}
